apiVersion: v1
kind: Service
metadata:
  name: simpleweb
  labels:
    app.kubernetes.io/name: simpleweb
spec:
  selector:
    app.kubernetes.io/name: simpleweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
