apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
  labels:
    app.kubernetes.io/name: simpleweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simpleweb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simpleweb
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: simpleweb
          image: yeasy/simple-web:latest
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10 
